network:
    domain: enovance.com
    bridge: virbr1
    gateway: 192.168.134.1
general:
    ssh_key: /home/jenkins/.ssh/id_rsa
edeploy:
    dir: /var/lib/debootstrap/install/D7-F.1.0.0/openstack-full/
hosts:
  -
    address: 192.168.134.48
    name: os-ci-test4
  -
    address: 192.168.134.51
    name: os-ci-test7
  -
    address: 192.168.134.52
    name: os-ci-test8
  -
    address: 192.168.134.53
    name: os-ci-test9
  -
    address: 192.168.134.54
    name: os-ci-test10
  -
    address: 192.168.134.55
    name: os-ci-test11
  -
    address: 192.168.134.56
    name: os-ci-test12
  -
    address: 192.168.134.57
    name: os-ci-test13
