network:
    domain: enovance.com
    bridge: virbr1
    gateway: 192.168.0.1
general:
    puppet_host: os-ci-test4
    puppet_cfg_dir: /home/sbadia/dev/enovance.com/lxc-edeploy/
    ssh_key: /home/sbadia/.ssh/id_rsa_seb.pub
edeploy:
    dir: /var/lib/debootstrap/install/D7-F.1.0.0/openstack-full
hosts:
  -
    address: 192.168.0.45
    name: os-ci-test1
  -
    address: 192.168.0.46
    name: os-ci-test2
  -
    address: 192.168.0.47
    name: os-ci-test3
  -
    address: 192.168.0.48
    name: os-ci-test4
  -
    address: 192.168.0.49
    name: os-ci-test5
  -
    address: 192.168.0.50
    name: os-ci-test6
  -
    address: 192.168.0.51
    name: os-ci-test7
  -
    address: 192.168.0.52
    name: os-ci-test8
  -
    address: 192.168.0.53
    name: os-ci-test9
  -
    address: 192.168.0.54
    name: os-ci-test10
  -
    address: 192.168.0.55
    name: os-ci-test11
  -
    address: 192.168.0.56
    name: os-ci-test12
  -
    address: 192.168.0.57
    name: os-ci-test13
