network:
    domain: yanisguenane.fr
    bridge: default
    gateway: 192.168.122.1
general:
    ssh_key: /home/yguenane/.ssh/id_rsa.pub
    lxc_dir: /var/lib/lxc
    tmp_dir: /tmp/lxc
edeploy:
  dir: /var/lib/debootstrap/install/D7-H.1.0.0
hosts:
  -
    address: 192.168.122.48
    name: os-ci-test4
    role: openstack-full
  -
    address: 192.168.122.49
    name: os-ci-test5
    role: openstack-full
