network:
    domain: enovance.com
    bridge: virbr1
    gateway: 192.168.0.1
general:
    ssh_key: /home/goneri/.ssh/id_rsa.pub
edeploy:
    dir: /var/lib/debootstrap/install/centos-F.1.0.0/openstack-full
hosts:
  -
    address: 10.68.0.48
    name: os-ci-test4
  -
    address: 10.68.0.51
    name: os-ci-test7
  -
    address: 192.168.0.52
    name: os-ci-test8
  -
    address: 192.168.0.53
    name: os-ci-test9
  -
    address: 192.168.0.54
    name: os-ci-test10
  -
    address: 192.168.0.55
    name: os-ci-test11
  -
    address: 192.168.0.56
    name: os-ci-test12
  -
    address: 192.168.0.57
    name: os-ci-test13
