general:
    ssh_key: /home/yguenane/.ssh/id_rsa.pub
    lxc_dir: /var/lib/lxc
    tmp_dir: /tmp/lxc
    edeploy_dir: /var/lib/debootstrap/install/D7-H.1.0.0
hosts:
  -
    address: 192.168.122.48
    name: os-ci-test4
    role: openstack-full
    memory: 2048
    vcpu: 2
    network: tmpen0vance
  -
    address: 192.168.134.49
    name: os-ci-test5
    role: openstack-full
    memory: 2048
    vcpu: 2
    network: tmpen0vance42
networks:
  -
    name: tmpen0vance
    type: bridge
    domain: yanisguenane.fr
    gateway: 192.168.122.1
  -
    name: tmpen0vance42
    type: bridge
    domain:  enovance.fr
    gateway: 192.168.134.1
